### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by sobolevn** [bobthemighty/punq#1]
Hi, @bobthemighty! 

I have really enjoyed both [your article](https://io.made.com/dependency-injection-with-type-signatures-in-python/) and the `punq` itself. Thanks for it!

I am searching for DI/IoC framework that will:
1. Use type annotations to inject dependencies
2. Not use any kind of decorators or any other extra syntax
3. Support wide range of types

This project looks like a perfect fit!
But, I am quite scared that it very immature. And it looks unsupported. 

Can you please tell me what is the status of this project? 
Maybe you can recommend some other tools that will fulfil my requirements?

**Comment by sobolevn** [comment]
@bobthemighty thanks for your answer! I have described my desired use-case in this issue https://github.com/dry-python/dependencies/issues/74

And since `punq` almost meets my needs, I am just wondering about:
1. performance, I am fine with "not too bad", but a benchmark would be a perfect feature!
2. singletons support for expensive dependencies, like db connectors, etc
3. handling complex types, including `ClassVar`, `Final`, etc

I am pretty happy to help with almost every aspect in the list 🙂

**Comment by bobthemighty** [comment]
Closing this, since the project is as alive as people want it to be :)

**Comment by sobolevn** [comment]
@bobthemighty thanks for your time and will to help! 👍
