### ISSUE TITLE
Typed file

### ISSUE THREAD

**Issue by dineshbvadhia** [bobthemighty/punq#177]
Is a Typed file available for punq?

**Comment by bobthemighty** [comment]
No, but I might take a look at this. The major blocker is that you can use any key to resolve any dependency. i think I might release a v2.0 that doesn't allow that flexibility, but can make type guarantees in exchange.

**Comment by dineshbvadhia** [comment]
Sounds good :) Typed libraries are becoming a de-facto requirement. Will close Issue.
