### ISSUE TITLE
Latest binding from the container without instantiation

### ISSUE THREAD

**Issue by michael-rubel** [bobthemighty/punq#186]
Another feature we might contribute is the ability to get the latest bound class for the given `service_key`, but without instantiating it.

### Why?

Let's imagine the following scenario:

```
client_input = self.container.registered(ClientInput) # This method doesn't exist currently. Only to describe the concept.

self.container.register(ClientInput, factory=lambda: client_input(**data))
```

After getting the latest registered class, you want to manually instantiate it (with the data from request), and then re-register the filled object inside the container. This way external modules can replace the implementation of the class with their own on stages where the client data is still unavailable.

This scenario should resolve the issue of handling Pydantic objects that should be fulfilled during the application lifecycle without explicitly adding Pydantic support to container.

Suggested shorter syntax for this feature:
```
self.container.rebind(ClientInput, args=**data)
```

Step-to-step behavior:
- Get the latest bound class for the key (without instantiation).
- Create a callback with the arguments passed to the class constructor.
- Instantiate the class with these arguments when resolved anywhere in the app.
- Additionally: ability to make the rebound class a singleton when instantiated for the first time, then reused.

---

**Comment by bobthemighty** [comment]
I don't have a strong opinion on your proposed solution, but I am confused by your use case.

Why can't you just register the ClientInput at the time that you have it? Or, rather, why would you register it before you knew what the implementation would be?

From what you're saying, it seems like you want to place an inbound request into the container? That'll vary per-request, and there's no support in punq, right now, for request scopes - only transient and singleton scopes. Leaving that aside, I'm not sure why this is better than explicitly passing the ClientInput to the things that need it.

**Comment by michael-rubel** [comment]
@bobthemighty This can be partially mitigated by #184, as you'll be able to resolve the object without registering it, but only in cases when you don't need a factory to instantiate it.

The use case is about external modules. They should be able to register their customized implementation of my object. When the main app fetches the object from the container, it should receive custom implementation as long as the external module is loaded. It's the main app doing "heavy lifting" to fulfill the object. My only need is to swap the class from the userland app level, not to enforce the overriding of the entire behavior.

**Comment by bobthemighty** [comment]
I understand every word in your message, but I'm still not following what you're trying to achieve.

I can image some set up like

```python

class MyPlugin:
    def register(self, container: Container):
        ....
```

Where a host application requests that some other module perform registration, but if that's the intended use case, why would `self.container.registered(Foo)` return anything? Why would you register it from the main app if you couldn't yet instantiate it?

Can you give a concrete example of what this pattern enables?

**Comment by michael-rubel** [comment]
The registration is currently required by punq's design, so this part was only to avoid instantiation of objects that can't live without valid data. The second part is about creating it with a valid data, and then rebinding it back to the container but of course the swapped version of the object if applicable.

You can try to make a Pydantic DTO registered as a service inside the container to make it easily swappable from external modules, but the modules shouldn't be responsible for the data the object receives when it's instantiated.

**Comment by bobthemighty** [comment]
I'd really like to see whether I can solve your use-case, but I still don't understand it. I'm happy to jump on a discord call or something, but if you could explain, without resort to abstraction, what it is that you want to _do_, I can work out whether it's a pattern that punq should support, and what the most appropriate implementation would be.

Reading between the lines, I imagine that you want to be able to inject some statically typed client request into a request handler. I am still unclear on the nature of the relationship between the "external modules" and the host application. I am still unclear as to why you would register the type at all if it can't actually be resolved.

What are the host application and the external modules _doing_? What are the data that you want to use to build this object, and where do they come from? Why does the external module need to instantiate that object, and why does it need to be registered by the host before the external module re-registers it? 

I'm not _personally_ a fan of injecting a client request into a handler, but my personal opinion on your design isn't super relevant. I would at least like to understand the intended lifetime of the injected object. As I mentioned before, punq does not currently have a per-request scope, which means that a client request can not be sensibly managed. To support per-request scope,we would first need a per-request context bag, and some way of relating that to the current request in the host application.

**Comment by michael-rubel** [comment]
@bobthemighty Why are you focusing on managing requests? It would be pretty much the same if we had a CLI script (we'd pass console arguments instead of the request). It's all about lifecycle hooking and flexibility.

Let's imagine we had a "service provider" abstraction layer where you can register all the services in the service container. These "service providers" are consumed by the core application (it scans the local app, as well as external modules, if there are any service providers available). Providers register dependencies **once** when the Python script starts. Then we have a **runtime** execution where actual dependencies are resolved, and where the actual input can be captured. To avoid collecting providers in runtime, we do it **once** per worker, for performance reasons obviously. If the external module's provider wants to swap the implementation of **any** stateful bag inside the core app, it cannot do this currently because the core app registers the dependency in runtime (service provider from external module is already registered the customization logic on the boot stage) to fulfill the required data and be consumed later on.

The solution for this is:
- Resolving dependencies dynamically (allowing instantiation without registration inside the container, when it's available as an import).
- Adding the ability to fetch the service key without actually instantiating it to allow re-registering of the retrieved service key inside the container.

The solution I came up **for now** is to create a factory for my stateful bag. Then the creation logic became swappable within that stateless factory (since it doesn't require any data to be instantiated). But this forces you to create a dummy object for every stateful bag, which I don't like.

In simple words, I want to do this:
```
request.app.container.register(
    service=ClientInput,
    factory=lambda: self.client_input_factory.create(data=body),
)
```
But without having a factory for every data bag. And of course `ClientInput` passed to the `service` key should be swappable by external modules.

I hope this was more understandable. 😄

**Comment by bobthemighty** [comment]
It is more understandable, and I promise I'm getting there :)

> It would be pretty much the same if we had a CLI script (we'd pass console arguments instead of the request)

I would still describe this as a request, I'm not necessarily thinking of an HTTP request. A request might be an async event, or any other message sent to a system to ask it to do a thing.
A CLI script is _slightly_ different, though, in that the process is single-request - it executes one request and exits - whereas in an HTTP application, or an event-daemon, the process is multi-request. That means that if you register a stateful object, you need to scope its lifetime.

That's not true if you register a stateless factory, which is why I would personally prefer that design. A "ClientinputFactory" is a service - it's a domain object with no identity that performs useful work; a "ClientInput" is not a service, it's a value object. Its purpose is to hold state.

> The solution I came up for now is to create a factory for my stateful bag. Then the creation logic became swappable within that stateless factory (since it doesn't require any data to be instantiated)

This makes sense to me.

>  But this forces you to create a dummy object for every stateful bag, which I don't like.

This does not. Why do you need to create a dummy object to have a swappable factory? Here's a gist where I can swap the implementation of input parsers without dummy objects of any kind: https://gist.github.com/bobthemighty/c73e1a439630ecffd9f93bbcc655fb13

None of this especially matters though -what matters is that *if you want to have a stateful bag injected from the container, then you need to define how that state should be managed*. Your container, per your description, is per-worker, but I expect that your stateful bag should _not_ be per-worker, but per ClientInput? If I've misunderstood that, then great!

If you want a per-ClientInput container (one per request, per event, per command line invocation, whatever), then you need to have a scoped container, something like:

```python
# Create the per-worker container
container = configure_all_the_things()

# Create a copy of that container, per-request, which stores some extra piece of state
request_container = container.child()

# Now our request-specific container can have a ClientInput registered that won't interfere
# with the ClientInput of any other invocation.
request_container.register(ClientInput, MyInputType(**data.body)
```

That's a pattern I've seen in some frameworks, which can be useful for - eg - automatic database transaction management.

I still don't understand where your ClientInput type is defined. If it's defined by an external module, then how can it have a registration managed by the host, rather than the external module? If it's managed by the external module, then why do you need to register a dummy?

**Comment by bobthemighty** [comment]
That's okay. What's your timezone?

I promise I'm not being difficult, i just want to understand what your actual problem is so that

A) I can help you to find a solution
B) I can make sure the design of punq - a small, explicit, non-magic DI container - remains consistent :)

**Comment by michael-rubel** [comment]
Sure, `Europe/Warsaw` timezone.

**Comment by bobthemighty** [comment]
Splendid. I'm Europe/London, and I'm free all day tomorrow if you want to do office-hours, otherwise I can do most evenings. Bob@codefiend.co.uk - drop me an invite.

**Comment by michael-rubel** [comment]
@bobthemighty Done! I've sent the invite via Google Meet.
