### ISSUE TITLE
resolve_all method docs

### ISSUE THREAD

**Issue by tigrus** [bobthemighty/punq#19]
Hello. 

I'm using and enjoying your lib in couple of projects. 

I've found method [`resolve_all`](https://github.com/bobthemighty/punq/blob/master/punq/__init__.py#L345).

It's not clear, when and why developer will use it. Can you write down some thoughts on it in docstring?

**Comment by bobthemighty** [comment]
@tigrus does this help: https://github.com/bobthemighty/punq/pull/20 ?

**Comment by tigrus** [comment]
@bobthemighty yep, that's what we wanted :) Thanks 👍

**Comment by tigrus** [comment]
Solved in #20
