### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by sobolevn** [bobthemighty/punq#2]
Hi, @bobthemighty! That's me again 🙂 

I am currently using `punq` in a side-project. It looks awesome!
So, I have decided to write some user-related documentation.
And maybe add some improovments as well, I will open new issues for things I find the most important.

And I know, that this might be sensitive. 
Do you have anything that you want to cover?

Also, you can check out our set of projects we are working right now: https://github.com/dry-python
It has its own DI framework which is awesome too.

**Comment by bobthemighty** [comment]
From my point of view, most of the docs are currently in docstrings. I was going to set up Sphinx with Readthedocs to auto-generate the API documentation. I usually use a README.rst with links to the rest of the documentation and some simple examples as in https://github.com/madedotcom/photon-pump

**Comment by bobthemighty** [comment]
Hey yo, @sobolevn!

How's this for a first attempt? https://punq.readthedocs.io/en/latest/

I need to fix the api autogeneration. I think I just need to make sure we're installing the module in the environment when we run spinx. Then there'll be a few things still to tweak, but it's a start.

**Comment by sobolevn** [comment]
@bobthemighty that's a good start! I will try to improve it when the first version will be merged.

**Comment by sobolevn** [comment]
@bobthemighty just published an article about `punq`, maybe you will like it https://sobolevn.me/2019/03/enforcing-srp

**Comment by bobthemighty** [comment]
Closing this, pending more specific and recent feedback
