### ISSUE TITLE
Improve sphinx template

### ISSUE THREAD

**Issue by sobolevn** [bobthemighty/punq#22]
Currently `sphinx` template misses several important features:

<img width="1280" alt="Снимок экрана 2019-05-31 в 17 05 13" src="https://user-images.githubusercontent.com/4660275/58711014-466fb500-83c6-11e9-97a3-8f1415afd992.png">

1. It does not have a clear github link from the main page
2. It does not show the number of stars on the main page (that's very important!)

Here are some good examples of how we can style it:
<img width="1280" alt="Снимок экрана 2019-05-31 в 17 07 14" src="https://user-images.githubusercontent.com/4660275/58711170-93ec2200-83c6-11e9-8d0e-738efe34323c.png">
Notice this gitlab-corner that is visible on the main page.

<img width="343" alt="Снимок экрана 2019-05-31 в 17 07 05" src="https://user-images.githubusercontent.com/4660275/58711171-93ec2200-83c6-11e9-8370-a34cb4828ae0.png">

Notice this big information about stars and a clear link to github.

**Comment by bobthemighty** [comment]
Happy to accept a PR :)
