### ISSUE TITLE
Introduce ValidateBeforeResolve concept 

### ISSUE THREAD

**Issue by sobolevn** [bobthemighty/punq#23]
I have faced a problem with my code that is not related to `punq`, but can be solved by it in a very interesting way.

I had a service that had a dependency on `redis`. I used `punq` to inject `redis` to it.
The problem was that I had a configuration problem: my `redis` url was incorrect. And I was not aware of that. My service started as it should, then when my cache was hit for the first time - everything broke apart.

How can this be prevented? By adding a new concept: `ValidateBeforeResolve` class.

That's what I am talking about written in Ruby: https://github.com/davydovanton/rubyjobs.dev/tree/master/system/boot

In Python it would be something like that:

```python
from punq import ValidateBeforeResolve

class RedisContainer(ValidateBeforeResolve):
     # Is inside base class, has the same semantic as `.register()`:
     # https://github.com/bobthemighty/punq/blob/master/punq/__init__.py#L210
     # def __init__(...): ...
 
     def validate(self) -> 'bool | Exception':
          self.instance.redis.ping()  # raises Exception if fails
          return true 
```

The thing I don't like about this is that we have to write classes for each validation. We can try to build API around `lambda` or functions.

Would be happy to hear your feedback.

**Comment by bobthemighty** [comment]
I would strongly recommend against baking complexity into an IOC container.

If I wanted this behaviour, I think I'd probably do it in the dependency itself eg.

```
class ScoreCache:

    def __init__(self, host='localhost', port=6379):
         # do whatever you gotta do, man.
         self.instance = redis.Redis(host, port)
         self.instance.ping()
 
    def incr_score(self):
        ...

    def decr_score(self):
        ....
```

It's not the responsibility of the ioc container to know how to test all your config for you, it's the responsibility of the consuming code.

**Comment by sobolevn** [comment]
Fair enough!
