### ISSUE TITLE
Best practices for isolating unrelated dependency instantiation?

### ISSUE THREAD

**Issue by jbcpollak** [bobthemighty/punq#25]
Hi, I'm looking forward to using punq, but I'm a bit confused about something. Is there a recommended way to setup conditional registrations of services? For example:

```
if Config.something_is_true:
    container.register(Service, ServiceImpl1)
else:
    container.register(Service, ServiceImpl2)
```

as the code and service-construction logic gets more complicated, don't want this all in the main file, and it doesn't make sense for the main file to be aware of all the possible implementations.

I'd like to organize it more sensibly, either with something like:

```
    # ServiceFactory somehow has access to the container so it can get access to Config
    container.register(Service, provider=ServiceFactory)
```

or perhaps:

```
    ServiceFactory.register(container)
```

I think the second option is the only thing practical right now, but I was wondering if that's the best practice.

**Comment by bobthemighty** [comment]
Hi @jbcpollak 

Sorry for the delay. I like the second option, and the reason I didn't immediately respond is that I thought punq _did_ that out of the box, and I went to check, and then I forgot what I was doing because I'm old and confused.

I'd happily accept a PR that fixed the issue, or I can take a look at some point.

**Comment by bobthemighty** [comment]
@jbcpollak I updated yesterday so that the container contains itself, and shipped that as 0.4.1 - does that fix your problem, or do you think we need something else? I need to write some docs at some point for both that and your scope change.

**Comment by jbcpollak** [comment]
Hum, I hadn't thought of that, let me update our code and think about how we can use this. I think it might be helpful - we can now inject the Context itself into classes right?

Is it possible to do injection into a function? It might be helpful to be able write factory functions that take the Context as a parameter, and then just register() the factory.

Let me take a look, this week is going to be busy I may not get a chance to respond right away.

Thanks for thinking about this!

**Comment by bobthemighty** [comment]
@jbcpollak I'm closing this one, given that we last talked about it 2 years ago. If adding the container to registry did _not_ solve your problem, feel free to open a new issue

> I may not get a chance to respond right away

:joy:

**Comment by jbcpollak** [comment]
Fair enough - we've been using the container in the registry for a while and so far so good. It's not perfect, but punq isn't what's slowing down our development so it's all good over here!

Ty!

**Comment by bobthemighty** [comment]
If you've got outstanding wishlist items that aren't in the issues already,
I'd be interested to know.

I've changed jobs and am actually writing code again. I'm keen to get punq
to a 1.0
