### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by sobolevn** [bobthemighty/punq#3]
I can definitetly can help with this one.

I will provide a working configuration for `python3.6` and onwards, 
but I will need a helping hand from @bobthemighty.

Can you please enable Travis CI builds for this repo?

**Comment by bobthemighty** [comment]
Travis is now enabled for the repo.

**Comment by bobthemighty** [comment]
I've opened a PR #5 for setting up travis, just copy-pasta from some of my other projects. Hopefully I'll have a working build later today and then you can go crazy. #4 is looking trickier.
