### ISSUE TITLE
Error when registering an abstract class

### ISSUE THREAD

**Issue by bustawin** [bobthemighty/punq#37]
Trying to register an abstract class (abc.ABC) fails.

The problem is in the following statement of the `register_concrete_service`:

```python
if not type(service) is type:
```

If you change it by the following:

```python
 if not inspect.isclass(service):
```

Then it works well.

(After using a few container libraries this is the only one I can happily use without messing up my architecture :-). Thank you!)

**Comment by louwers** [comment]
We ran into this as well. Please fix. :pray:

**Comment by bustawin** [comment]
If @bobthemighty wants I can do a PR.

**Comment by bobthemighty** [comment]
A PR would be very welcome @bustawin !

**Comment by louwers** [comment]
@bobthemighty Can you merge it?

**Comment by bobthemighty** [comment]
Merged! Thanks @louwers

**Comment by louwers** [comment]
This can be closed.
