### ISSUE TITLE
Coverage badge is broken

### ISSUE THREAD

**Issue by sobolevn** [bobthemighty/punq#38]
It looks like this:
<img width="329" alt="Снимок экрана 2020-05-17 в 11 42 45" src="https://user-images.githubusercontent.com/4660275/82139845-9a6fe580-9833-11ea-9754-eb54c8153ceb.png">

And leads to some abandoned place: https://codecov.io/gh/bobthemighty/punq

**Comment by bobthemighty** [comment]
Fixed by #51
