### ISSUE TITLE
Measure code/test coverage

### ISSUE THREAD

**Issue by sobolevn** [bobthemighty/punq#4]
Currently there are some tests, but I am not sure how many lines of the project is actually covered. 
I will enable coverage for the project and CI #3, but I will also need some help from @bobthemighty.

Please, enable https://coveralls.io/ when you will have some free time.

**Comment by bobthemighty** [comment]
Coveralls is now enabled.

**Comment by sobolevn** [comment]
@bobthemighty awesome! I will contribute soon.

**Comment by bobthemighty** [comment]
Codecov is going to be a pain, actually, because of the test framework I used. I might rip that out and rewrite to pytest.

**Comment by sobolevn** [comment]
@bobthemighty I have actually never seen this framework before. Will have a look.

**Comment by bobthemighty** [comment]
@sobolevn Not suprising :) It was written by a friend of mine some years ago. I like it a lot for business process stuff, but I've stopped using it for library work. Another co-worker [wrote a pytest plugin](https://pypi.org/project/pytest-contexts/) that provides the same syntax but that's got some problems of its own.

**Comment by bobthemighty** [comment]
I'm doing the conversion to pytest this morning as a precursor to both this and #6
