### ISSUE TITLE
Callable singletons are registered incorrectly 

### ISSUE THREAD

**Issue by sobolevn** [bobthemighty/punq#6]
# Bug report

## Problem

Let's say I have a class like this:

```python
class RunSomeQuery(object):
    def __init__(self, db):
         self._db = db
    def __call__(self, arg):
         return self._db.query(arg)
```

And then I register it as a singleton:

```python
import punq

container = punq.Container()
container.register(RunSomeQuery, RunSomeQuery(db=my_db_instance))
```

The problem is that this line: https://github.com/bobthemighty/punq/blob/master/punq/__init__.py#L122
decides that this class is callable. And registers it as an implementation.

I still expect it to be registered as a singleton instance.

## Proposed solution

Add a special kwarg to register singletons: `container.register(BaseClassName, singleton=Instance())`
Possibly, there are other solutions as well.

**Comment by sobolevn** [comment]
I think that singletons itself are special cases. And should be treated differently. 

This way one can decide how to use this class:

```python
class RunSomeQuery(object):
    def __init__(self, db):
         self._db = db
    def __call__(self, arg):
         return self._db.query(arg)
```

As a factory or as a singleton. Which is not clear from the difinition. And we can make a wrong decision.

**Comment by bobthemighty** [comment]
Hi @sobolevn - I've just opened #8 which provides an explicit kwarg `instance` for registering an explicit instance.

I've avoided the term `singleton` because it's not technically true. One explicit design goal for punq is to avoid global state, so you can create multiple containers each containing a different explicit instance.

```
container1 = Container()
container2 = Container()

container1.register(EmailSender, instance=SmtpEmailSender())
container1.register(EmailSender, instance=SmtpEmailSender())
```
