### ISSUE TITLE
String annotations causes `NameError`

### ISSUE THREAD

**Issue by sobolevn** [bobthemighty/punq#9]
When I use string annotations `punq` raises `NameError`.

## Example

```python
import attr
import punq

@attr.s(auto_attribs=True)
class Test(object):
    dep: 'Dependency'


@attr.s(auto_attribs=True)
class Dependency(object):
    val = 1


print(Test(Dependency()).dep.val)
#=> 1

container = punq.Container()
container.register(Dependency)
container.register(Test)

print(container.resolve(Test).dep.val)
#=> NameError: name 'Dependency' is not defined
```

## Stacktrace

```
Traceback (most recent call last):
  File "manage.py", line 19, in <module>
    container.register(Test)
  File "/Users/sobolev/Documents/PyCharmProjects/kira/.venv/lib/python3.6/site-packages/punq/__init__.py", line 122, in register
    self.registrations.register(service, _factory, **kwargs)
  File "/Users/sobolev/Documents/PyCharmProjects/kira/.venv/lib/python3.6/site-packages/punq/__init__.py", line 102, in register
    self.register_concrete_service(service)
  File "/Users/sobolev/Documents/PyCharmProjects/kira/.venv/lib/python3.6/site-packages/punq/__init__.py", line 96, in register_concrete_service
    self._get_needs_for_ctor(service),
  File "/Users/sobolev/Documents/PyCharmProjects/kira/.venv/lib/python3.6/site-packages/punq/__init__.py", line 22, in _get_needs_for_ctor
    sig = typing.get_type_hints(cls.__init__)
  File "/Users/sobolev/.pyenv/versions/3.6.6/lib/python3.6/typing.py", line 1543, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/Users/sobolev/.pyenv/versions/3.6.6/lib/python3.6/typing.py", line 350, in _eval_type
    return t._eval_type(globalns, localns)
  File "/Users/sobolev/.pyenv/versions/3.6.6/lib/python3.6/typing.py", line 245, in _eval_type
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Dependency' is not defined
```

## Versions

python: 3.6.6
punq: 0.0.4

## Consideration

I guess that it might be the same issue with `from __future__ import annotations`.

**Comment by bobthemighty** [comment]
I'm struggling to understand what you're trying to achieve here.

```
@attr.s(auto_attribs=True)
class Test(object):
    dep: Dependency
```

This works fine. 

The problem is that when you use a string as the type hint, we're unable to create a constructor signature for your class. That's not a punq problem per se. It can be seen in the following snippet:

```
import typing
from dataclasses import dataclass

@dataclass
class foo:
    bar: 'bar'

print(typing.get_type_hints(foo.__init__))
```

This exhibits exactly the same behaviour, since the generated constructor for `foo(bar)` can't be interrogated by the typing module.

I *can* fetch the constructor signature via the annotations property like this:

```
>>> print(foo.__init__.__annotations__)
{'bar': 'bar', 'return': None}
```

But that doesn't really solve the problem unless you've explicitly registered the type `bar` as the implementation of the service `"bar`" in the container. What exactly are you trying to do?

**Comment by sobolevn** [comment]
Ok, sorry for the bad explanation. Here's my use-case.

I have two modules: `a.py` and `b.py`. And `b.py` imports stuff from `a.py`.
And one class from `a.py` is using type annotation from `b.py`. So, I have to use a code like that to avoid circular imports:

```python
# a.py
from typing import TYPE_CHECKING

if TYPE_CHECKING:
     from b import Dependency  # noqa


@attr.s(auto_attribs=True)
class Test(object):
    dep: 'Dependency'

...
```

This way I am able to define types the way it does not fail on circular imports.
And it perfectly valid way to do it without https://www.python.org/dev/peps/pep-0563/ 

I can see other use-cases for string annotations as well. But, I am not sure how to treat them correctly at the moment.

**Comment by bobthemighty** [comment]
oooookay! It's a forward declaration? That makes some sense. In particular it explains why the typing module is trying to evaluate the type.

Seems like there's a known issue in the typing module that was backported to Python 3.7. I'll have a think and a read through the typing module to see if anything jumps out.

**Comment by bobthemighty** [comment]
LOL! So the reason this happens is that when the typing module tries to resolve a type for a ForwardRef, it does so by walking the mro of the inspected type and checking the `__globals__` of the declaring module. In your case, that means we inspect the type Test, ask it for its module - a - and then inspect the `__globals__` of a to find `Dependency` which _obviously_ isnt' going to be there or you wouldn't have used a ForwardRef in the first place. I have a couple of ideas here:

1. Use `inspect` to figure out what the localns ought to be when we actually come to the registration. Provided the name `Dependency` is declared or imported _somewhere_ in the frame where you call `container.register` we'd be able to figure out what you meant. Obviously this has some weird edge cases that might bite people. There's some overhead to walking the call stack, but this is something that should only be happening during app startup so it's probably fine.

2. Use the names of the currently registered services as the `localns` argument to `get_type_hints`. That would solve the problem if and only if you'd already registered `Dependency` but I note that you tried that so I'm guessing other users would _also_ try that.

3. Mark it as a known issue and wait for a fix upstream.

**Comment by bobthemighty** [comment]
I'm definitely leaning toward option 2, I think. There's still the possibility of unexpected behaviour but only if:

1. you've registered an implementation that depends on a forward declaration
2. you've separately registered a service with that name.

In return, it offers us the possibility of a simple workaround to this problem that's easily documented: If you use a forward ref, you need to register that forward ref first.

**Comment by sobolevn** [comment]
@bobthemighty what to do with names like `module_name.ClassName`?

**Comment by sobolevn** [comment]
Maybe leaving an option is a good idea?

```python
container = punq.Container()
container.register(Dependency, alias='module_name.Dependency')
```

**Comment by bobthemighty** [comment]
@sobolevn that already works,

```
container.register('module_name.Dependency', Dependency)
```
